import CustomNav from "@/Components/CustomNav/CustomNav";
import { Box } from "@/Components/CustomNav/Box";
import { Content } from "@/Components/CustomNav/Content";
import { Providers } from "./providers";
import { Layout } from "@/Components/CustomNav/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <main>
            <Layout>
              <Box>
                <Content>{children}</Content>
              </Box>
            </Layout>
          </main>
        </Providers>
      </body>
    </html>
  );
}
