import { Box } from "@/Components/CustomNav/Box";
import { Content } from "@/Components/CustomNav/Content";
import { Layout } from "@/Components/CustomNav/Layout";
import { Providers } from "../providers";
import CustomNav from "@/Components/CustomNav/AdminNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <CustomNav />
      <Layout>
        <Box>
          <Content>{children}</Content>
        </Box>
      </Layout>
    </Providers>
  );
}
