import CustomNav from "@/Components/CustomNav/CustomNav";
import { Box } from "@/Components/CustomNav/Box";
import { Content } from "@/Components/CustomNav/Content";
import { Layout } from "@/Components/CustomNav/Layout";
import { Providers } from "../providers";

export const metadata = {
  title: "Hajurko Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <CustomNav />
      <Layout>
        <Box>
          <Content>{children}</Content>
        </Box>
      </Layout>
    </Providers>
  );
}
